standard:
    phpSettings:
        date:
            timezone: UTC
        post_max_size: 20M
        upload_max_filesize: 8M
        display_startup_errors: 0
        display_errors: 0
    
    bootstrap:
        path: "{APPLICATION_PATH}/Bootstrap.php"
        class: Bootstrap
    
    resources:
        frontController:
            moduleDirectory: "{APPLICATION_PATH}/modules"
        layou:
            layoutPath: "{APPLICATION_PATH}/layouts/scripts"
        
    data:
        connection:
            username: "root"
            password: ""
            database: "project"
            driver: "mysql"
            hostname: "localhost"
            port: ""
        connection_string: ""
        models_path: "{APPLICATION_PATH}/models"
        dump_path: "{APPLICATION_PATH}/data/dump"
        fixtures_path: "{APPLICATION_PATH}/data/fixtures"
        migrations_path: "{APPLICATION_PATH}/data/migrations"
        sql_path: "{APPLICATION_PATH}/data/sql"
        yaml_schema_path: "{APPLICATION_PATH}/data/schema"
        yaml_schema_file_path: "{APPLICATION_PATH}/data/schema/schema.yml"
        extensions_path: "{DOCTRINE_EXTENSIONS_PATH}"
        dump_path: "{APPLICATION_PATH}/data/dump"
        models:
            generate: true
            options:
                pearStyle: true
                baseClassesDirectory: null
                baseClassPrefix: "Base_"
                classPrefix: ""
                classPrefixFiles: false
        autoloader: "zend"
        compile:
            generate: true
            use: false
            path: "{LIBRARY_PATH}/Doctrine.compiled.php"
            drivers:
                - "mysql"
    
    locale:
        locale: "en_AU"
        timezone: "Australia/Perth"
        currency: "AUD"
    
    mail:
        send_email: true
        from:
            name: "BalCMS System"
            address: "balcms@balupton.com"
        log: # Where Error Logs will be sent to
            name: "Balupton Log"
            address: "log@balupton.com"
        transport:
            smtp:
                host: "localhost"
    
    payment:
        gateway: ""
        default:
            store_path: "{LOGS_PATH}/payment"
        paypal:
            url: "https://www.paypal.com/cgi-bin/webscr"
            token: ""
            business: ""
            notify_url: "{SCRIPTS_URL}/payment/paypal/ipn.php"
            return: "{SCRIPTS_URL}/payment/paypal/pdt.php"

    site:
        name: "Your New Website" # Used in text throughout the site
        title: "My New Website" # Used in the page title
        separator: " - " # Used to sperarate page titles
        generator: "BalCMS - http://www.balupton.com/projects/balcms"
        author:
            title: "Site Admin's Name"
            email: ""
            website: ""
            
    error:
        friendly: true
        throw: false
        template: error
        
    setup:
        secret: "secret"
        salt: "salt"
        
    auth:
        remember: "+2 weeks"
        
    log:
        store: true
        request: true
        
    paging:
        items: 2
        chunk: 5
    
    services:
        analytics:
            code: false
        reinvigorate:
            code: false
        gsfn:
            company: false
        
    areaThemes:
        default: "titan"
