
# ==============================================
# BALCMS CONTENT

Balcms_Content:
    actAs:
        SoftDelete:
        Bal_Doctrine_Template_Auditable:
            status:
                disabled: false
            Author:
                disabled: false
            authorstr:
                disabled: false
            created_at:
                disabled: false
            updated_at:
                disabled: false
            published_at:
                disabled: false
        Searchable:
            fields: [code, tags, authorstr, title, description]
        Taggable:
            tagAlias: "ContentTags"
    columns:
        id:
            primary: true
            type: integer(2)
            unsigned: true
            autoincrement: true
        code:
            type: string(30)
            notblank: true
            unique: true
        title:
            type: string(50)
            notblank: true
        tagline:
            type: string(100)
        description:
            type: string
            notblank: true
            extra:
                html: rich
        description_rendered:
            type: string
            notblank: true
            extra:
                html: rich
        description_auto:
            type: bool
            notnull: true
        tags:
            type: string(255)
        content:
            type: string
            notblank: true
            extra:
                html: rich
        content_rendered:
            type: string
            notblank: true
            extra:
                html: rich
            
        position:
            type: integer(2)
            unsigned: true
            notnull: true
            default: 0
        type:
            type: enum
            values: [content,event]
            default: content
            notblank: true
            
        Avatar_id:
            type: integer(2)
            unsigned: true
        Route_id:
            type: integer(2)
            unsigned: true
            unique: true
        Parent_id:
            type: integer(2)
            unsigned: true
    relations:
        Avatar:
            class: File
            local: Avatar_id
            foreign: id
            foreignAlias: Contents
            onDelete: "SET NULL"
        Route:
            local: Route_id
            foreign: id
            foreignAlias: Contents
            onDelete: CASCADE
        Parent:
            class: Content
            local: Parent_id
            foreign: id
            foreignAlias: Children
            onDelete: CASCADE

Balcms_ContentProduct:
    inheritance:
        extends: Content
        type: column_aggregation
        keyField: type
        keyValue: product
    columns:
        product_cost:
            type: decimal(8)
            scale: 2
            #notblank: true
            extra:
                currency: true
        product_taxable:
            type: boolean
            default: true
        product_stock:
            type: integer(2)
            unsigned: true
            #notnull: true

Balcms_ContentBook:
    inheritance:
        extends: ContentProduct
        type: column_aggregation
        keyField: type
        keyValue: book
    columns:
        book_isbn:
            # Unique Identifier
            type: string(13)
        book_isn:
            # Before ISBN
            type: string(8)
        book_author:
            type: string(50)
            #notblank: true
        book_published:
            type: timestamp
        book_publisher:
            type: string(50)
        book_binding:
            type: enum
            values: [hardcover,softcover]
        book_edition:
            type: string(10)
        book_quality:
            type: enum
            values: [used,new,good]

Balcms_ContentEvent:
    inheritance:
        extends: Content
        type: column_aggregation
        keyField: type
        keyValue: event
    columns:
        event_start_at:
            type: timestamp
        event_finish_at:
            type: timestamp

# ==============================================
# BALCMS MESSAGE

Balcms_Message:
    inheritance:
        extends: Bal_Message
        type: simple
    columns:
        content_id:
            type: integer(2)
            unsigned: true
    relations:
        Content:
            class: Content
            local: Content_id
            foreign: id
            foreignAlias: Messages


# ==============================================
# BALCMS USER

Balcms_User:
    inheritance:
        extends: Bal_User
        type: simple
    actAs:
        Searchable:
            fields: [username,email,fullname,suburb,state,country]
            # This can only be listed once due to bug in doctrine
    columns:
        type:
            type: enum
            values: [user]
            notblank: true
            default: "user"
