---
detect_relations: false 

Route:
    actAs:
        Searchable:
            fields: [path]
    columns:
        id:
            primary: true
            type: integer(4)
            unsigned: true
        path:
            type: string(150)
            notblank: true
        type:
            type: string(15)
            notblank: true
        data:
            type: array

Page:
    actAs:
        Searchable:
            fields: [code]
        Versionable:
            versionColumn: version
            className: %CLASS%Version
            auditLog: true
            deleteVersions: true
        Timestampable:
    columns:
        id:
            primary: true
            type: integer(4)
            unsigned: true
        code:
            type: string(30)
            notblank: true
        title:
            type: string(50)
            default: true
        content:
            type: string
            extra:
                html: rich
        router:
            type: integer(4)
            unsigned: true
            unique: true
            notnull: true
    relations:
        Router:
            class: Router
            local: router_id
            foreign: id
            foreignAlias: Items
            
Page:
    inheritance:
        extends: Item
        type: concrete
                
Event:
    inheritance:
        extends: Item
        type: concrete
    columns:
        start:
            type: timestamp
        finish:
            type: timestamp

Comment:
    inheritance:
        extends: Item
        type: concrete
        