production: &production
    <<<: *balcms
    mail:
        from:
            name: "BalCMS System"
            address: "balcms@balupton.com"

staging: &staging
    <<<: *production
    mail:
        from:
            name: "BalCMS System: Staging"
            address: "staging.balcms@balupton.com"

testing: &testing
    <<<: *production
    phpSettings:
        display_startup_errors: 1
        display_errors: 1
    error:
        friendly: false
        throw: false
    mail:
        from:
            name: "BalCMS System: Testing"
            address: "testing.balcms@balupton.com"

development: &development
    <<<: *production
    phpSettings:
        display_startup_errors: 1
        display_errors: 1
    error:
        friendly: false
        throw: false
    data:
        models:
            generate: true
        compile:
            generate: true
    mail:
        send_email: false
        from:
            name: "BalCMS System: Development"
            address: "development.balcms@balupton.com"
    log:
        store: true
    editor:
        code: aloha
