balcms: &balcms
    phpSettings:
        date:
            timezone: UTC
        post_max_size: 20M
        upload_max_filesize: 8M
        display_startup_errors: 0
        display_errors: 0
    
    bootstrap:
        path: "<?=APPLICATION_PATH?>/Bootstrap.php"
        class: Bootstrap
    
    resources:
        frontController:
            moduleDirectory: "<?=MODULES_PATH?>"
        layout:
            layoutPath: "<?=APPLICATION_PATH?>/layouts/scripts"
        
    data:
        connection_string: sqlite:///<?=DATABASES_PATH?>/<?=APPLICATION_ENV?>.db
        models_path: "<?=MODELS_PATH?>"
        dump_path: "<?=DATA_DUMP_PATH?>"
        fixtures_path: "<?=DATA_FIXTURES_PATH?>"
        migrations_path: "<?=DATA_MIGRATIONS_PATH?>"
        sql_path: "<?=DATA_SQL_PATH?>"
        extensions_path: "<?=DOCTRINE_EXTENSIONS_PATH?>"
        yaml_schema_path: "<?=DATA_SCHEMA_PATH?>"
        yaml_schema_file_path: "<?=DATA_SCHEMA_COMPILED_FILE_PATH?>"
        yaml_schema_includes:  
            - "<?=APPLICATION_PATH?>/data/schema/schema.yml"
            - "<?=MODELS_PATH?>/Bal/Schema/Invoice.yml"
            - "<?=MODELS_PATH?>/Bal/Schema/File.yml"
            - "<?=MODELS_PATH?>/Bal/Schema/Message.yml"
            - "<?=MODELS_PATH?>/Bal/Schema/Route.yml"
            - "<?=MODELS_PATH?>/Bal/Schema/User.yml"
            - "<?=MODELS_PATH?>/Balcms/Schema/Schema.yml"
        models:
            generate: true
            options:
                pearStyle: true
                baseClassesDirectory: null
                baseClassPrefix: "Base_"
                classPrefix: ""
                classPrefixFiles: false
        autoloader: "zend"
        compile:
            generate: true
            use: false
            path: "<?=LIBRARY_PATH?>/Doctrine.compiled.php"
            drivers:
                - "mysql"
    
    locale:
        locale: "en_AU"
        timezone: "Australia/Perth"
        currency: "AUD"
    
    mail:
        send_email: true
        from:
            name: "BalCMS System"
            address: "balcms@balupton.com"
        log: # Where Error Logs will be sent to
            name: "Balupton Log"
            address: "log@balupton.com"
        transport:
            smtp:
                host: "localhost"
        
    payment:
        gateway: "paypal"
        default:
            store_path: "<?=LOGS_PAYMENT_PATH?>"
        paypal:
            url: "https://www.paypal.com/cgi-bin/webscr"
            token: ""
            business: ""
            notify_url: "<?=SCRIPTS_URL?>/payment/paypal/ipn.php"
            return: "<?=SCRIPTS_URL?>/payment/paypal/pdt.php"

    site:
        name: "Your New Website" # Used in text throughout the site
        title: "My New Website" # Used in the page title
        description: "Your New Website's Description" # Used in the meta data
        keywords: "your, new, websites, keywords" # Used in the meta data
        separator: " > " # Used to sperarate page titles
        generator: "BalCMS - http://www.balupton.com/projects/balcms"
        version: "0.10.0-dev Sydney"
        author:
            title: "Site Admin's Name"
            email: ""
            website: ""
            
    error:
        friendly: true
        throw: false
        template: error
        
    setup:
        secret: "secret"
        salt: "salt"
        
    auth:
        remember: "+2 weeks"
        
    log:
        store: true
        request: true
        
    paging:
        items: 15 # how many items should be displayed on a page
        chunk: 5 # how many page numbers should be displayed
    
    services:
        analytics:
            code: false
        reinvigorate:
            code: false
        gsfn:
            company: false
        
    areaThemes:
        default: titan
        back: balcms
        front: titan
    
    routing:
        defaults:
            routeTable: Route
            pathColumn: path
            typeColumn: type
            dataColumn: data
            routeKey: Route
            firstAsHome: false
        routeTypes:
            default:
                module: balcms
            content:
                controller: front
                action: content-page
            events:
                controller: front
                action: events-page
            event:
                controller: front
                action: event-page
                
    widgets:
        viewpath: widgets
        widget:
            vimeo:
                helper: social
            youtube:
                helper: social
            url:
                helper: content
            code:
                helper: content
            comments:
                helper: content
            subscribe:
                helper: content
            eventlist:
                helper: content
            taglist:
                helper: content
            contentlist:
                helper: content
            gallery:
                helper: gallery
    
    content:
        cache: true # should we use the rendered content cache?
    
    editor:
        code: tinymce
    
    hours_in_work_day: 8
    invoice:
        tax_rate: 0.10
        commission: 0
        company:
            name: "Your Company's Name"
            address1: "Your Company's Address"
            address2: ""
            suburb: "Your Company's Suburb"
            state: "Your Company's State"
            country: "Your Company's Country"
            postcode: "Your Company's Postcode"
    
    compilers:
        csscaffold:
            config:
                system: "<?=CSSCAFFOLD_COMPILER_PATH?>/"
                cache: "<?=CACHE_STYLES_PATH?>"
                cache_lifetime: 3600
                enable_log: true
                error_threshold: 1
                gzip_compression: false
            options:
            	
        scaffold:
            config:
                system: "<?=SCAFFOLD_PATH?>/"
                urlpath: "<?=PUBLIC_PATH?>"
                production: "<?=PRODUCTION_MODE?>"
                enable_url: true
                enable_string: false
                set_etag: true
                output_compression: false
                import_paths:
                    - "<?=SCAFFOLD_PATH?>/imports"
                max_age: false
                extensions:
                    - "AbsoluteUrls"
                    - "Embed"
                    - "Functions"
                    - "HSL"
                    - "ImageReplace"
                    - "Minify"
                    - "Properties"
                    - "Random"
                    - "Import"
                    - "Mixins"
                    - "NestedSelectors"
                    - "Variables"
                    - "XMLVariables"
