balcms: &balcms
    # Core
    CONFIG_PATH: >
        <?=APPLICATION_PATH?>/config
    CONFIG_COMPILED_PATH: >
        <?=CONFIG_PATH?>/compiled

    # Configuration Paths
    CONFIG_FILE_PATH: >
        <?=CONFIG_PATH?>/balcms.yml<?=PATH_SEPARATOR?><?=CONFIG_PATH?>/application.yml
    NAVIGATION_FILE_PATH: >
        <?=CONFIG_PATH?>/nav.yml
    ROUTES_FILE_PATH: >
        <?=CONFIG_PATH?>/routes.yml
    INSTALLED_FILE_PATH: >
        <?=APPLICATION_ROOT_PATH?>/application/data/logs/installed
    CONFIG_COMPILED_FILE_PATH: >
        <?=CONFIG_COMPILED_PATH?>/application.data
    NAVIGATION_COMPILED_FILE_PATH: >
        <?=CONFIG_COMPILED_PATH?>/nav.data
    ROUTES_COMPILED_FILE_PATH: >
        <?=CONFIG_COMPILED_PATH?>/routes.data

    # Configuration
    DEBUG_SECRET: >
        <?=md5(APPLICATION_ROOT_PATH)?>
    DEBUG_MODE: >
        auto
    PROFILE_MODE: false

    # Urls
    ROOT_URL: >
        http://<?=HTTP_HOST?>
    BASE_URL: >
        auto

    # Libraries
    DOCTRINE_PATH: >
        <?=COMMON_PATH?>/doctrine1/lib
    DOCTRINE_EXTENSIONS_PATH: >
        <?=COMMON_PATH?>/doctrine-extensions
    ZEND_PATH: >
        <?=COMMON_PATH?>/zend-v1.10.7-lib
    BALPHP_PATH: >
        <?=COMMON_PATH?>/balphp-v1.0/lib
    HTMLPURIFIER_PATH: >
        <?=COMMON_PATH?>/htmlpurifier-v4.2.0-lib
    PHPCLOSURE_PATH: >
        <?=COMMON_PATH?>/php-closure'

    # Data Locations
    DATA_PATH: >
        <?=APPLICATION_ROOT_PATH?>/application/data
    DATA_DUMP_PATH: >
        <?=DATA_PATH?>/dump
    DATA_FIXTURES_PATH: >
        <?=DATA_PATH?>/fixtures
    DATA_MIGRATIONS_PATH: >
        <?=DATA_PATH?>/migrations
    DATA_SQL_PATH: >
        <?=DATA_PATH?>/sql
    DATA_SCHEMA_PATH: >
        <?=DATA_PATH?>/schema
    DATA_SCHEMA_COMPILED_PATH: >
        <?=DATA_SCHEMA_PATH?>/compiled
    DATA_SCHEMA_COMPILED_FILE_PATH: >
        <?=DATA_SCHEMA_COMPILED_PATH?>/schema.yml

    # Application Locations
    DATABASES_PATH: >
        <?=DATA_PATH?>/database
    LOGS_PATH: >
        <?=DATA_PATH?>/logs
    LOGS_PAYMENT_PATH: >
        <?=LOGS_PATH?>/payment
    MODELS_PATH: >
        <?=APPLICATION_ROOT_PATH?>/application/models
    MODELS_BASE_PATH: >
        <?=MODELS_PATH?>/Base
    MODULES_PATH: >
        <?=APPLICATION_ROOT_PATH?>/application/modules
    IL8N_PATH: >
        <?=APPLICATION_ROOT_PATH?>/il8n
    SCRIPTS_PATH: >
        <?=APPLICATION_ROOT_PATH?>/scripts
    SCRIPTS_URL: >
        <?=BASE_URL?>/scripts

    # Public Locations
    PUBLIC_PATH: >
        <?=APPLICATION_ROOT_PATH?>/public
    PUBLIC_URL: >
        <?=BASE_URL?>/public
    THEMES_PATH: >
        <?=APPLICATION_ROOT_PATH?>/public/themes
    THEMES_URL: >
        <?=BASE_URL?>/public/themes
    PUBLIC_STYLES_PATH: >
        <?=APPLICATION_ROOT_PATH?>/public/styles
    PUBLIC_STYLES_URL: >
        <?=BASE_URL?>/public/styles
    PUBLIC_SCRIPTS_PATH: >
        <?=APPLICATION_ROOT_PATH?>/public/scripts
    PUBLIC_SCRIPTS_URL: >
        <?=BASE_URL?>/public/scripts
    MEDIA_PATH: >
        <?=APPLICATION_ROOT_PATH?>/public/media
    MEDIA_URL: >
        <?=BASE_URL?>/public/media
    MEDIA_DELETED_PATH: >
        <?=APPLICATION_ROOT_PATH?>/public/media/deleted
    MEDIA_DELETED_URL: >
        <?=BASE_URL?>/public/media/deleted
    MEDIA_IMAGES_PATH: >
        <?=APPLICATION_ROOT_PATH?>/public/media/images
    MEDIA_IMAGES_URL: >
        <?=BASE_URL?>/public/media/images
    MEDIA_INVOICES_PATH: >
        <?=APPLICATION_ROOT_PATH?>/public/media/invoices
    MEDIA_INVOICES_URL: >
        <?=BASE_URL?>/public/media/invoices
    MEDIA_UPLOADS_PATH: >
        <?=APPLICATION_ROOT_PATH?>/public/media/uploads
    MEDIA_UPLOADS_URL: >
        <?=BASE_URL?>/public/media/uploads

    # Cache Paths
    CACHE_PATH: >
        <?=DATA_PATH?>/cache
    CACHE_SCRIPTS_PATH: >
        <?=MEDIA_PATH?>/cache/scripts
    CACHE_SCRIPTS_URL: >
        <?=MEDIA_URL?>/cache/scripts
    CACHE_STYLES_PATH: >
        <?=MEDIA_PATH?>/cache/styles
    CACHE_STYLES_URL: >
        <?=MEDIA_URL?>/cache/styles

    # Include Paths
    INCLUDE_PATHS: >
        <?=LIBRARY_PATH?><?=PATH_SEPARATOR?><?=MODELS_PATH?>

production: &production
    <<: *balcms
    BASE_URL: ""

staging: &staging
    <<: *balcms
    
testing: &testing
    <<: *balcms
    
development: &development
    <<: *balcms
    CONFIG_FILE_GENERATE: true
